import "./globals.css";
import "swiper/swiper.min.css";
import "swiper/css/navigation";
import { Inter } from "next/font/google";
import React from "react";
import Layout from "../components/layout";
import Providers from "../components/providers/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YOKRENT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Layout>
            <main>{children}</main>
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
